### ISSUE TITLE
Two Emoji are undefined/missing

### ISSUE THREAD

**Issue by ianknauer** [joeattardi/emoji-button#10]
Hey there, the two following emoji are running into rendering issues for both Firefox and chrome on OSX (they seem to be fine in Safari). I've checked the [unicode listing](http://unicode.org/emoji/charts/full-emoji-list.html) and relaxed doesn't seem to exist? White frowning face does exist, so i'm not sure what would cause the rendering issues here.

1. Relaxed
<img width="679" alt="relaxed" src="https://user-images.githubusercontent.com/2685721/67970593-7b2ba680-fbc8-11e9-8b96-b3835fb69708.png">

2. white_frowning_face 
<img width="647" alt="white_frowning_face" src="https://user-images.githubusercontent.com/2685721/67970628-87afff00-fbc8-11e9-8e96-226a77e14714.png">

**Comment by joeattardi** [comment]
Oops! Turns out I was not specifying the emoji fonts, which was causing these two emojis to render wrong for some reason. I just released version 2.1.2 which should fix this issue. Thanks!
