### ISSUE TITLE
[Feature] Expose emoji name on selected

### ISSUE THREAD

**Issue by boyanio** [joeattardi/emoji-button#105]
Currently, when an emoji is selected, an event is emitted with the emoji itself. However, it would be nice to have the name too. What do you think? I can help with a PR :)

**Comment by joeattardi** [comment]
I could definitely see this being useful! Certainly, feel free to submit a PR! Thanks!

**Comment by boyanio** [comment]
You can check my PR when you have time. I'll appreciate your feedback :-)

**Comment by joeattardi** [comment]
Im planning on taking a look later today. Thanks for the contribution!

**Comment by boyanio** [comment]
@joeattardi Thanks for merging my PR! When do you plan to create a new release? We have a use case soon, so we'd be happy to use it :)

**Comment by joeattardi** [comment]
I just released version 4.2.0 which should include your PR 😄

**Comment by boyanio** [comment]
Great timing - thank you! :-)
