### ISSUE TITLE
Cdn version?

### ISSUE THREAD

**Issue by Hoodgail** [joeattardi/emoji-button#107]
id there a CDN version?

**Comment by joeattardi** [comment]
Emoji Button is available on all the standard CDNs such as unpkg, jsDelivr, etc. For example:

https://unpkg.com/@joeattardi/emoji-button

https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@latest/dist/index.min.js

**Comment by GarrettAlbright** [comment]
There's issues with those currently. I tried both URLs.

Safari reports "SyntaxError: Unexpected keyword 'export'" and Chrome reports a similar error. Firefox reports "Uncaught SyntaxError: export declarations may only appear at top level of a module."

I don't really know anything about JS outside of the browser context but I'm guessing there's something about how those CDN versions are packaged that aren't compatible with in-browser use.

I guess I could build it myself as per the README but I'd prefer to use a CDN version as I don't use Node/NPM and would rather avoid installing it if I can, so it'd be really cool if we can get some working CDN versions.

**Comment by joeattardi** [comment]
To use an ES module natively in supported browsers (Safari, Chrome, and Firefox all support them), you need to use a `<script type="module">` tag to load.

In general, your `<script type="module">` should point to a JS file of your own, which imports Emoji Button from the CDN URL. 

So your `app.js` would have this:

```javascript
import { EmojiButton } from 'https://unpkg.com/@joeattardi/emoji-button@4.3.0/dist/index.js';

const picker = new EmojiButton();
// etc.
```

Then in your HTML you would have this tag:

```html
<script type="module" src="app.js"></script>
```

Here's a quick and dirty CodePen that shows how this works:

https://codepen.io/thinksInCode/pen/vYKbQdV
