### ISSUE TITLE
Option to not autofocus search bar

### ISSUE THREAD

**Issue by midzer** [joeattardi/emoji-button#11]
Hi 😃

on mobile I experience that keyboard opens up right after click on emoji-button. This is because its search bar gets autofocus. Especially on small screens this situation covers much of the screen. Maybe users want to click/browse through emojis instead of searching for them on first hand.

How about making it optional that searchbar gets autofocus on open.

I would be happy to contribute PR if you're interested.

Have a nice week
midzer

**Comment by joeattardi** [comment]
Thanks for the suggestion!

I have just released version 2.2.0 which implements this, there is a new `autoFocusSearch` option.
