### ISSUE TITLE
Error with Bootstrap 4 modal

### ISSUE THREAD

**Issue by dnwilson** [joeattardi/emoji-button#110]
This throws an error onfocus when displayed withing a bootstrap modal and an emoji is clicked

**Comment by joeattardi** [comment]
Can you share any other details?

What's the specific error being thrown, what's the stack trace look like?

Can you provide some sample code?

Thanks!

**Comment by joeattardi** [comment]
@dnwilson Hello again, could you supply some more detail about the error you're getting?

**Comment by dnwilson** [comment]
@joeattardi sorry for the delay for some reason I'm not getting notifications. See below for the stack trace. It's related to [this](https://stackoverflow.com/questions/35758658/bootstrap-modal-focus-not-working) which is an issue with bootstrap modal not being able to identify which element has focus.

<img width="649" alt="Screen Shot 2020-10-08 at 2 33 19 PM" src="https://user-images.githubusercontent.com/2078506/95500616-08e54980-0975-11eb-8222-bb54325f1525.png">

```
      var _this5 = this;
      $(document).off(EVENT_FOCUSIN) // Guard against infinite focus loop
      .on(EVENT_FOCUSIN, function (event) {
        if (document !== event.target && _this5._element !== event.target && $(_this5._element).has(event.target).length === 0) {
          _this5._element.focus();
        }
      });
    };
```

**Comment by joeattardi** [comment]
Bootstrap 5 is the current now, closing this.

**Comment by triptate** [comment]
It seems like this is still an issue in Bootstrap 5, although the error doesn't seem to interrupt desired behavior (i.e. the picker still works).

**Comment by JD-Robbs** [comment]
I am experiencing this very same error in Bootstrap 5. :)

**Comment by JD-Robbs** [comment]
> I am experiencing this very same error in Bootstrap 5 (though the picker doesn't work in my case - unlike what triptate is seeing). :)

To "fix" it: set `data-bs-focus` to `false` and then set the `z-index` of `.emoji-picker__wrapper` to `9999`.

**Comment by Tafitson** [comment]
For anyone coming across this problem (especially with older bootrap versions):
Setting the rootElement property of EmojiButon (see https://emoji-button.js.org/docs/api) to the Modal-Element fixed this problem for me with Bootstrap 3.

**Comment by iamsid** [comment]
On BS5, getting the same issue when in modal.
Setting rootElement worked for me as suggested by @Tafitson .
