### ISSUE TITLE
Twemoji loads PNG's instead of SVG's for recent emoji

### ISSUE THREAD

**Issue by mnz2000** [joeattardi/emoji-button#111]
Emojis on the Recent list are loaded as PNG as opposed to all the others that load as SVG.

I believe this was working before, but got reverted in this commit: https://github.com/joeattardi/emoji-button/commit/cfc128da4f2ce7e02cabb1aaaa8655d257c15658#diff-811f31ddb8463a7149f1ce34f4b7d2f76c42be49c301629301c37c09645a890c

twemojiOptions should not have been removed, and it should be passed to the twemoji.parse() function.

**Comment by joeattardi** [comment]
Just released version 4.4.0 which includes your PR that addresses this.
