### ISSUE TITLE
CSS should respect the main site's styles

### ISSUE THREAD

**Issue by mnz2000** [joeattardi/emoji-button#116]
The emoji-button.css should NOT set the following properties:

font-size
font-family (except the Emoji font families)

There may well be others but these two messed up my site's design. I have a custom font that should be used site-wide. I have set the base font size larger (18px) to make all text on the site larger. This should apply to the Emoji Button as well.

Additionally, I had to add the following to the .emoji-picker style:

  box-sizing: content-box;

This is because my site sets 'border-box' on the html element and 'inherit' on *. I believe this is quite a common setting. The emoji-button CSS relies on border-box sizing so it should set that explicitly.

**Comment by joeattardi** [comment]
So the way I addressed this was I kept the font family and size that I set, but I set them as CSS variables and added support in the picker for overriding those CSS variables. So you should be able to set your custom font, colors, etc. Hopefully this will fit your use case! See https://emoji-button.js.org/docs/styleCustomization for an example.

I just released version 4.3.0 which includes this feature.
