### ISSUE TITLE
New emojis display as missing glyphs

### ISSUE THREAD

**Issue by ardeliatay** [joeattardi/emoji-button#119]
![Screen Shot 2020-11-02 at 11 22 07 AM](https://user-images.githubusercontent.com/40645496/97911239-c870b580-1cff-11eb-8486-5618de698b8d.png)
 
On version 4.2.0, newer emojis (emojiVersion 12.0 or later) are displaying as missing glyph symbols.  Tested in latest Chrome and Firefox.  Font used is Apple Color Emoji.  Workaround is setting emojiVersion to '11.0' - all emojis in this version display correctly.  Any ideas? Thanks

**Comment by joeattardi** [comment]
What macOS version are you running?

**Comment by ardeliatay** [comment]
@joeattardi Mojave version 10.14.5

**Comment by joeattardi** [comment]
Ah, I think that's the issue. I am pretty sure Emoji 12.0 is only supported in Catalina.

**Comment by ardeliatay** [comment]
Ah okay that would explain it! Thanks!
