### ISSUE TITLE
Possible to install without npm/yarn?

### ISSUE THREAD

**Issue by tanjyeyee** [joeattardi/emoji-button#121]
Hi there,

I'm from the dinosaur era and thus I'm still using Javascript/JQuery, how does this library work for vanilla JS?

Any JSFiddle/CodePen that I can view?

**Comment by joeattardi** [comment]
You can use it without a bundler but you will need to use a modern browser that supports ES modules. I will try to find a few minutes tonight or tomorrow to create a CodePen demonstrating this, as it looks like the previous one I posted had expired.

Will get back to you tomorrow.

**Comment by tanjyeyee** [comment]
Thanks Joe, really appreciate the speed with which you got back to me.

**Comment by tanjyeyee** [comment]
Hello Joe, any updates on this?

Perhaps it would be good to also include this under the "Installation" section.

I really appreciate this so thank you in advance.

**Comment by joeattardi** [comment]
Hi, sorry for the delay on this.

I have created a new CodePen showing how to use Emoji Button without npm or a bundler.

Caveat, you do need to be using a browser that supports ES modules (this is all modern browsers now, IE11 won't work though)

Here's the codepen:

https://codepen.io/thinksInCode/pen/vYKbQdV

It's a very simplified example, but I think it clearly shows how to use it. Please let me know if you still have questions or issues and I'll see if I can help!

I'll leave the issue open for now but feel free to close it if you have what you need. Thanks!

**Comment by redbrain** [comment]
Hi Joe,
I'd also like to thank you for the example. As a traditional JS developer, this was useful to begin, but I do have a question.

Is it possible to access `EmojiButton` from the window itself? A page I work on has many elements, some created dynamically.
It would be easier to call `togglePicker` in the element instead of defining all the buttons in a module outside of the page.

Thanks for your work on the project by the way, it's invaluable to me!

**Comment by joeattardi** [comment]
Hi @redbrain - The current method you are using is the preferred way. Specifying the `onclick` handler as a string of JavaScript directly in the button's attribute is not usually a good practice.

You're better off doing what you've done here - using `document.getElementById` or `document.querySelector` to select the trigger button, and programmatically add an event listener as you've done in your sample code.

Hope this help!

**Comment by ZaDarkSide** [comment]
A compiled version that works with a AMD loader is available?

**Comment by joeattardi** [comment]
@ZaDarkSide Unfortunately not. Emoji Button is published as an ES Module only.

**Comment by ZaDarkSide** [comment]
I would really need a compiled version AMD or UMD compatible. Others too, i would suggest to use webpack and add a `dist` folder with the compiled version in npm package like other libs have.

**Comment by joeattardi** [comment]
Versions of Emoji Button prior to 4.0.0 published a UMD module. However, I made the conscious decision after 4.0.0 to only support modern browsers that support ES modules. These are now supported in all major browsers except Internet Explorer, which is no longer supported.

**Comment by bediu** [comment]
> However, I made the conscious decision after 4.0.0 to only support modern browsers that support ES modules.

I am very grateful for your open source project, but that is a completely unnecessary decision. I have to use another emoji picker now.

**Comment by joeattardi** [comment]
> I am very grateful for your open source project, but that is a completely unnecessary decision. I have to use another emoji picker now.

You're entitled to your opinion but I disagree. We are almost in 2021 and the only browser that doesn't support ES modules natively is IE11. Emoji Button already uses other features not supported by IE11 (CSS variables for example) so there is little reason not to use ES modules at this point.

**Comment by bediu** [comment]
> We are almost in 2021 and the only browser that doesn't support ES modules natively is IE11.

That's all very fine and very clear. I don't even support IE11 myself. But what you're doing here is not just removing support for IE11, but also enforcing a development pattern. It's perfectly fine, and it will be perfectly fine to code a webapp without the use of ES modules.

**Comment by joeattardi** [comment]
You can still use a bundler and transpile the code if you don't want to use ES modules. There are other libraries that do this as well. 

Thanks for your opinion.
