### ISSUE TITLE
Feature Request: Press key arrow down inside search input should focus on emojis below it

### ISSUE THREAD

**Issue by chanlito** [joeattardi/emoji-button#122]
I think the title is pretty clear.

**Comment by joeattardi** [comment]
This can already be done by using the `Tab` key to focus between the different areas of the UI.

**Comment by chanlito** [comment]
@joeattardi I know `Tab` key works, but `ArrowDown` feels more natural. Or at least provide events such as on `picker.on('search-focus')` or something.
