### ISSUE TITLE
Breaking change in 4.5.0 ?

### ISSUE THREAD

**Issue by qortex** [joeattardi/emoji-button#124]
This code doesn't type anymore:

```ts
 this.picker.on('emoji', (emoji) => {
      this.log.info(`Emoji selected: ${emoji.emoji}`); ... });
```

```
error TS2339: Property 'emoji' does not exist on type 'string'.

94       this.log.info(`Emoji selected: ${emoji.emoji}`);
```

And indeed, the typing seems to have changed:

```sh
on(event: string, callback: (arg: string) => void): void;
```

Is it on purpose, or is it a typing glitch?
Thanks!

**Comment by qortex** [comment]
I was using 4.3.0 before, and pinning to `4.4.0` gives another typing error (below).

Maybe a good policy would be to give default value to new parameters? Or maybe it was done in 4.5.0 actually :)

Note: a changelog would be awesome to quickly pinpoint the changes :)

```
error TS2345: Argument of type '{ position: "bottom"; recentsCount: number; showSearch: false; showRecents: false; showVariants: true; emojiVersion: "12.1"; zIndex: number; i18n: { search: string; categories: { recents: string; ... 9 more ...; custom: string; }; notFound: string; }; }' is not assignable to parameter of type 'Options'.
  Property 'twemojiStyle' is missing in type '{ position: "bottom"; recentsCount: number; showSearch: false; showRecents: false; showVariants: true; emojiVersion: "12.1"; zIndex: number; i18n: { search: string; categories: { recents: string; ... 9 more ...; custom: string; }; notFound: string; }; }' but required in type 'Options'.

 60   picker = new EmojiButton({
                               ~
 61     position: 'bottom',
    ~~~~~~~~~~~~~~~~~~~~~~~
... 
 84     },
    ~~~~~~
 85   });
```

**Comment by joeattardi** [comment]
Agghh! I'm sorry about this. I had changed to have TypeScript automatically generate the typings instead of manually specifying them; obviously I didn't test this as thoroughly as I should. I will try to get this resolved later today, very sorry about the inconvenience!

**Comment by joeattardi** [comment]
I have just corrected the typings and released version 4.5.1. I will deprecate both 4.5.0 and 4.4.0 since they both have incorrect typings. Sorry again about that! I will try to publish more detailed changelogs moving forward.

**Comment by qortex** [comment]
Awesome, thanks for the quick fix!

Out of curiosity, why did you prefer going for `any` instead of the more precise `EmojiEventData` type? I understand it may be linked to the fact the types are generated automatically? Interested to understand a bit of how that works.

**Comment by joeattardi** [comment]
There is another public event, `hidden`, that is fired when the picker is hidden. The callback to handle that event doesn't take any arguments, so I couldn't use `EmojiEventData`. In fact, I just realized, the typing still isn't correct. The `on` and `off` functions expect a callback with one argument, but if you're listening for the `hidden` event, there isn't an argument specified in the callback. This would result in a typing error as well! I need to update the callback to make the single argument optional.
