### ISSUE TITLE
Can't find the files

### ISSUE THREAD

**Issue by fanthomas** [joeattardi/emoji-button#125]
Hello,
I'm **not using npm** and now I'm totally lost. I wanted to upgrade to the latest version but I can't find the files I need.
This is what I have (**3.1.1**), and now it's totally changed...

![image](https://user-images.githubusercontent.com/22766668/100442203-ee436d00-30a7-11eb-990a-b05ecbd4ad10.png)

Thank you !

**Comment by joeattardi** [comment]
If you're not using npm then you probably are best off loading the library from a CDN such as jsDelivr or unpkg.

**Comment by fanthomas** [comment]
Well, that is not convenient at all for us. Everyone doesn't use NPM...
Was way simpler before, can't make it work.
![image](https://user-images.githubusercontent.com/22766668/100513762-ebac4a80-316f-11eb-9cff-c643cc533ec4.png)

**Comment by fanthomas** [comment]
Just put the JS instead of the ancient version, doesn't work.

![image](https://user-images.githubusercontent.com/22766668/100513901-dd126300-3170-11eb-9370-e5e5f18ba793.png)

**Comment by fanthomas** [comment]
It's resolved. I had to add ![image](https://user-images.githubusercontent.com/22766668/100514437-07661f80-3175-11eb-9694-bc7240168f28.png) on my js script call.

**Comment by fanthomas** [comment]
Oh nice now this is an object, so much changes.
![image](https://user-images.githubusercontent.com/22766668/100514544-e225e100-3175-11eb-91e0-29cd84692313.png)

**Comment by joeattardi** [comment]
Going from 3.x to 4.x is a major version change. The whole point of a major version change is that there are breaking changes.

**Comment by joeattardi** [comment]
https://semver.org
