### ISSUE TITLE
Emoji-button for HTML/CSS and Javascript

### ISSUE THREAD

**Issue by pascalf22** [joeattardi/emoji-button#14]
Hello !
I really love Emoji-Button.
I have a question, can we add it to html page ?
I see in documentation that it's for Vanilla Javascript... but does it work for html page ?
Thanks a lot !

**Comment by joeattardi** [comment]
Yes, this will definitely work on a plain old HTML page with just some JavaScript.

Here's what you need to do:

Go to the [latest release](https://github.com/joeattardi/emoji-button/releases/tag/v2.4.0) and download the JavaScript file `emoji-button.min.js`. Then here's a basic example of how to use it:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Emoji Test</title>
    <script src="emoji-button.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        var picker = new EmojiButton();
        var button = document.querySelector('#emoji-button');
        button.addEventListener('click', function () {
          picker.showPicker(button);
        });
      });
    </script>
  </head>
  <body>
    <h1>Emoji Button</h1>
    <button id="emoji-button">😀</button>
  </body>
</html>
```

Hope this helps! Let me know if you still have problems. I'm going to close this for now.

**Comment by pascalf22** [comment]
Hello !
Thanks a LOT for your response. I will try it today !!
I really appreciate !
Have a great day !
Pascal

**Comment by pascalf22** [comment]
Hello Joe !
Thanks again :)
One more thing... can we increase the emoji size in emoji popup and also in the input ?

Thanks A LOT :)

Pascal

**Comment by pascalf22** [comment]
Hello...
For my last question... i know i can set font-size on the emoji popup list... but in the text fied, is it possible to only increase the font-size of the emoji without increase the other text?

Because on widows, emoji are not so beautiful... but when they are a bit bigger... they are a bit more beautiful...

thanks :)
