### ISSUE TITLE
Keep Emoji Picker Open

### ISSUE THREAD

**Issue by mattWalters0** [joeattardi/emoji-button#145]
Is it possible to keep the emoji picker open even if you click outside it?  

I'm trying to use the picker on a mobile screen and I would like it to be displayed all the time. Is there any way to achieve this with Emoji Button? 

Thanks!

**Comment by cyberfly** [comment]
@mattWalters0 you can https://emoji-button.js.org/docs/customize

**Comment by mattWalters0** [comment]
Thanks @cyberfly.  I saw this option but the Picker still closes if you click or tap outside it..  I really want it to be displayed all the time but not sure if that's possible...

**Comment by joeattardi** [comment]
Duplicate of #136, I will try to add support for this in v5.
