### ISSUE TITLE
Emoji picker container justify-content: space-between instead of center

### ISSUE THREAD

**Issue by LiviuAMDi** [joeattardi/emoji-button#152]
Using `justify-content: center` for the `.emoji-picker__container` results some weird space on the sides of the emojis grid. It would look better and use the real estate more efficient if `center` would be replaced with `space-between`.

Using `center`
<img width="395" alt="Screenshot 2021-05-06 at 11 16 35" src="https://user-images.githubusercontent.com/6162416/117273591-9120c400-ae5c-11eb-8900-87e197f6625d.png">

Using `space-between`
<img width="393" alt="Screenshot 2021-05-06 at 11 16 23" src="https://user-images.githubusercontent.com/6162416/117273607-95e57800-ae5c-11eb-9e33-e8c2660f28ff.png">

**Comment by joeattardi** [comment]
You're right, this does look better. I have already made this change in a refactor branch I'm working on and will be included in the upcoming v5 release. Thanks!
