### ISSUE TITLE
JoyPixels/Twemoji, and IE?

### ISSUE THREAD

**Issue by alexthekid07** [joeattardi/emoji-button#16]
Is there any way to use emoji from another library like JoyPixels?

**Comment by joeattardi** [comment]
Not currently. Emoji Button uses the actual Unicode emoji sequences, so they will always appear in the operating system's native style.

**Comment by alexthekid07** [comment]
Avoiding opening another issue, I wanted to see if the built-in OS emoji looked worked in IE and it doesn't seem to load the script properly. Is there any IE polyfill for Emoji-Button or is it just unsupported?

**Comment by joeattardi** [comment]
Oops! Looks like I was using arrow functions in the demo so it wasn't loading on IE. I fixed the demo so it loads in IE - IE11, at least - though I noticed a few quirks under IE. I will see if I can get a VM set up to try to debug some of the IE11 issues.

**Comment by joeattardi** [comment]
I just released version 2.5.3 which should have fixed IE11 support.
