### ISSUE TITLE
on emoji event does not work

### ISSUE THREAD

**Issue by Veeni2021** [joeattardi/emoji-button#163]
`const picker1 = new EmojiButton({
        showPreview: false,
        position: 'top-start',
        emojiVersion: '11.0',
        zIndex: 0,
        emojiSize: '1.5em',
        emojisPerRow: 12,
        rows: 4,
        rootElement: document.querySelector("elem")
    });

    picker1.on('emoji', selection => {
        alert(`"emoji" event fired, emoji is ${selection.emoji} with name ${selection.name}`);
    });`
    
    The above code to get the selected emoji returns undefined. Any way to get the selected emoji via code?

**Comment by joeattardi** [comment]
Can you share the full code? I just created this CodePen based on your code and it is working as expected:

https://codepen.io/thinksInCode/pen/bGqoJJw

**Comment by joeattardi** [comment]
Any update on this? I will close soon if there is no response.

**Comment by Veeni2021** [comment]
Hi Joe,

Apologies for not explaining, In https://www.npmjs.com/package/@joeattardi/emoji-button to get the selected emoji
`picker.on('emoji', selection => {
  // handle the selected emoji here
  console.log(selection.emoji);
});`

But this did not give any emoji, To make it work :
`
const button1 = document.querySelector('#emoji1');
const picker1 = new EmojiButton({
        showPreview: false,
        position: 'top-start',
        emojiVersion: '11.0',
        zIndex: 0,
        emojiSize: '1.5em',
        emojisPerRow: 12,
        rows: 4,
        autoHide: false,
        rootElement: document.querySelector("section.right")
    });
    picker1.on('emoji', emoji => {
    document.querySelector('#inputMessage').innerText += emoji;
});

button1.addEventListener('click', () => {
    picker1.togglePicker(button1);
});
`

**Comment by joeattardi** [comment]
Can you create a code pen or something that demonstrates the issue you're having? It would be a lot easier than trying to debug code snippets in an issue comment.

If I understand what you're saying correctly, this does not work:

```
picker.on('emoji', selection => console.log(selection.emoji));
```

But this does work?

```
picker.on('emoji', emoji => console.log(emoji));
```

Are you using the latest version of Emoji Button? A self contained, runnable example would really help here.

**Comment by Veeni2021** [comment]
In my code yes, but for this code pen no, as the link to 4.6.0 does not even open the emoji picker window.
Attached is a working link on selection gives undefined when emoji is selected.
[https://codepen.io/sdasdas08/pen/bGWVXQQ](url)

**Comment by joeattardi** [comment]
Your codepen is using version 3.0.3, which is over a year old. 

In that version, the `emoji` event is fired with simply the emoji character itself, rather than an object containing an `emoji` property (which is how the current 4.x version works).

Are you using version 3.x in your application as well? If so, is there a reason you don't want to use the latest version?

Anyway, there is no issue here other than you appear to be following the 4.x documentation for the 3.x version of Emoji Button. If you must stick with 3.x for some reason, you can see the 3.x README here: https://github.com/joeattardi/emoji-button/blob/v3.0.3/README.md

**Comment by Veeni2021** [comment]
[https://codepen.io/sdasdas08/pen/bGWVXQQ](url)
If I reference the 4.6.0 the emoji window does not even appear on click of the button.

**Comment by joeattardi** [comment]
You can't pull in version 4.x via a plain `script` tag. The current version of Emoji Button is only available as an ES module. I apologize if the documentation doesn't make this clear.

This should "just work" in an npm project, but to use it in a CodePen, for example, you need to import the ES module. In your example, you need to remove the `script` tag in the HTML, and add this line to the beginning of your JavaScript:

```javascript
import { EmojiButton } from 'https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@4.6.0/dist/index.min.js';
```

Then it should work as expected.

As I update the documentation for Emoji Button 5, I will make sure the docs are clearer on this.

**Comment by Veeni2021** [comment]
The latest is Emoji Button 5 now?
Thank you for the import statement yes the code pen now works, thank you!

**Comment by joeattardi** [comment]
Not quite yet. Currently 4.x is the current version. I am in the middle of a significant refactoring for version 5 which I hope to have done by the end of the summer. 

Apologies once again for the lack of detail in the documentation. The current doc site leaves a lot to be desired!
