### ISSUE TITLE
Flags are showing as letters instead of actual flag emojis

### ISSUE THREAD

**Issue by devildog3261** [joeattardi/emoji-button#169]
Flags are only showing as ISO codes instead of actual flag emojis.

![image](https://user-images.githubusercontent.com/55672860/131432719-dc336da7-a9e8-49b4-afde-278760bb9f9c.png)

![image](https://user-images.githubusercontent.com/55672860/131432818-7fa3a499-21be-44b0-a8fe-a76820255e8f.png)

**Comment by joeattardi** [comment]
What OS/browser are you running? This usually happens on a slightly out of date OS version which does not support the later Emoji versions which have those flags. 

If this is the case it should work if you use the twemoji style.

**Comment by devildog3261** [comment]
Edge - Version 92.0.902.84 (Official build) (64-bit) (most recent)
Chrome - Version 92.0.4515.159 (Official Build) (64-bit) (most recent)

**Comment by joeattardi** [comment]
Emoji support is usually dictated by the operating system, the system fonts have the glyphs that are implemented. What operating system/version are you on?

**Comment by devildog3261** [comment]
actually that's a good catch! I'm running on the most recent preview build of windows 11 right now. I can confirm it works correctly when using twemoji style. My apologies!

**Comment by joeattardi** [comment]
Looks like there is a known issue with Microsoft not supporting flag emojis, even in Windows 10:

https://answers.microsoft.com/en-us/windows/forum/all/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05
