### ISSUE TITLE
Need Option to Return Name of the Selected Emoji

### ISSUE THREAD

**Issue by shivam091** [joeattardi/emoji-button#181]
Hi,

I came across a situation where I need to persist name of the emoji into the database rather than storing direct emoji symbol, as I was doing till now.

Is there any option you can provide to return name (:emoji_name:) of the emoji (say e.g. ":cat:" / ":heart:", etc)
and some method to get emoji symbol if I pass this name as an argument.

Thanks in advance.

**Comment by joeattardi** [comment]
Currently Emoji Button doesn't support shortcodes. The emoji data already takes up a lot of space, the shortcodes would add a lot more.

You might be able to get this functionality from the [https://emojibase.dev/](Emojibase) library.
