### ISSUE TITLE
Its 2022 this should have been a Web component 

### ISSUE THREAD

**Issue by Danny-Engelman** [joeattardi/emoji-button#183]

**Comment by joeattardi** [comment]
The beauty of this library being vanilla JS based is that it's possible to wrap this in a React/Angular/Vue/Svelte component, or even a web component/custom element as you've indicated here. 

I can't meet everyone's demands and needs, this is not a full time job. 

If you need this as a web component then it should be pretty easy to wrap it up in one. I may even do that in the future, who knows. 

It's 2022, do people still need to be told not to harass open source maintainers?
