### ISSUE TITLE
Adding new emojis

### ISSUE THREAD

**Issue by ghidoz** [joeattardi/emoji-button#19]
Hi, I forked your library, updated the **emoji-datasource** library to the most recent version (5.0.1) and run the processEmojiData.js.

Apart from some problems with the categories array, that I manually fixed, now I have many empty emojis and also emojis composed by multiple ones. Any suggestions on how to fix it? Is there anything else I should update to make it work?

<img width="384" alt="Schermata 2020-01-23 alle 11 53 10" src="https://user-images.githubusercontent.com/7501260/72978637-1c488880-3dd7-11ea-9566-d6a42750c0c6.png">

It would be amazing if you could update the library, adding all the new missing emojis.
Thanks!

**Comment by joeattardi** [comment]
Hmm, I'm not sure why you were encountering that issue. I just updated to the latest `emoji-datasource` and after making a few category tweaks, everything seems to be working. I just released version 2.6.0 that should include the new emoji. Can you try it out at https://joeattardi.github.io/emoji-button and see if it is working for you?

Thanks!

**Comment by ghidoz** [comment]
Thanks for releasing the new version!
Actually I have the same problem also with yours:

<img width="383" alt="Schermata 2020-01-24 alle 10 21 51" src="https://user-images.githubusercontent.com/7501260/73058210-7444c500-3e93-11ea-9599-496f6cf48f6a.png">

It looks like the system emoji font on my Macbook Pro with macOs Mojave (v10.14.6) doesn't include the new emojis

**Comment by joeattardi** [comment]
Yes, I think that's the issue. I am running Catalina which has support for the new emojis. I don't know what really can be done about that.
