### ISSUE TITLE
Emoji quality in demo is very bad

### ISSUE THREAD

**Issue by AaronNGray** [joeattardi/emoji-button#2]
For some reason the emoji quality in the demo 
https://joeattardi.github.io/emoji-button is very bad as compared to the README.md picture.

**Comment by joeattardi** [comment]
A couple of questions:

1. What is your platform and browser?
2. Can you attach a screenshot?

Thank you!

**Comment by AaronNGray** [comment]
Looing at it in the cold light of day it looks like it just the black lines round the emoji's and the fact the ones on your README.md look slightly 3 dimensional being slightly spherical.

![emojis](https://user-images.githubusercontent.com/85523/64909202-fc0a0e00-d700-11e9-81f1-0c1f43cad1c9.png)

**Comment by joeattardi** [comment]
By your screenshot, it looks like you are on Windows, is that right? Emojis look differently on different operating systems - I took my screenshots on a Mac, but Windows and Linux have different images to represent the emojis. So it looks like Windows just doesn't have very nice looking emoji images. Unfortunately there's nothing I can do about that - Emoji Button is using the OS's built-in emojis characters, not images.

For example, see https://emojipedia.org/grinning-face/ - it shows the image for each platform.
