### ISSUE TITLE
Dependency warning on popperjs

### ISSUE THREAD

**Issue by MicMicMon** [joeattardi/emoji-button#20]
The last `yarn` update I did, I got this warning:
```
warning @joeattardi/emoji-button > popper.js@1.16.1: Popper changed home, find its new releases at @popperjs/core
```

Looks like the popperjs dependency should be updated :)

**Comment by joeattardi** [comment]
Fixed in v2.7.0.

**Comment by atomiks** [comment]
@joeattardi, in Popper 2 `margin` on the popper element is no longer considered and can cause problems. I see you have `0 0.5em` applied. 

We're may be adding a warning for this and adding an override for the next patch release: https://github.com/popperjs/popper-core/pull/972

**Comment by joeattardi** [comment]
Thanks for the heads up @atomiks - I will get rid of the `margin`.
