### ISSUE TITLE
Small vertical margin quirck

### ISSUE THREAD

**Issue by qortex** [joeattardi/emoji-button#21]
It looks like #12 is back in my project:

![image](https://user-images.githubusercontent.com/37897072/73054742-6e4ae600-3e8b-11ea-9cc9-c1221b0f187f.png)

Removing the `margin-top: 0.5em` fixes the issue for me:

![image](https://user-images.githubusercontent.com/37897072/73054764-80c51f80-3e8b-11ea-8e8a-f592ebc81fdb.png)

What do you think is the best way to fix it?

**Comment by joeattardi** [comment]
I can't seem to reproduce this behavior. What browser are you on?

**Comment by MicMicMon** [comment]
I'm using Vivaldi browser.

I guess it's related to the message in this issue: https://github.com/joeattardi/emoji-button/issues/20#issuecomment-578373479 ?

**Comment by MicMicMon** [comment]
Ah no, it's not the same CSS. For me, to fix the glitch described here, I do:
```
.emoji-picker__tab-body {
  margin-top: 0 !important;
}
```

**Comment by joeattardi** [comment]
Just wanted to let you know I haven’t forgotten about this. I am currently working on version 3.0 of the picker and will make sure to address this issue.

**Comment by qortex** [comment]
Interesting! Curious about v3 :)
I was thinking of doing an Angular package to ease integration in Angular projects. Never done it before though, so not sure when I'll find some time to look at how to properly do that.

That would add a ngx-emoji-button to the family :)

**Comment by joeattardi** [comment]
Hi, was wondering if you could try version 3.0.0 and see if this issue still exists for you? Thanks!

**Comment by qortex** [comment]
Hi! Sure, will do. Didn't have time to try yet, I'm in the middle of a pretty big refactoring and didn't plug the emojis back in. Will let you know as soon as I do it!

Thanks for the follow-up

**Comment by qortex** [comment]
Finally got around to updating!
Works fine, don't need the css workaround anymore.

And v3 looks awesome :) Didn't have to change code, worked out of the box.
Thanks for the work!
