### ISSUE TITLE
Bug when you press tab in searching input

### ISSUE THREAD

**Issue by Adizbek** [joeattardi/emoji-button#23]
The result, just pressed tab in search bar:

![image](https://user-images.githubusercontent.com/10253982/74085454-db20cb80-4a9a-11ea-8afb-ba3d49499538.png)

**Comment by joeattardi** [comment]
Yikes, that looks gross. I’ll take a look, thanks!

**Comment by joeattardi** [comment]
This should be fixed now in v2.7.3.
