### ISSUE TITLE
Recent smiles are hidding when click on smile

### ISSUE THREAD

**Issue by Adizbek** [joeattardi/emoji-button#24]
![image](https://user-images.githubusercontent.com/10253982/74088441-5e044f00-4ab8-11ea-99d9-46f950243d86.png)
When I click one of them, all they are gone 
![image](https://user-images.githubusercontent.com/10253982/74088450-6d839800-4ab8-11ea-88dd-723754c5bf73.png)
I need manually change category then they appear again

I used       autoHide: false

**Comment by joeattardi** [comment]
This should be fixed now in v2.7.3.

**Comment by Shah-ali** [comment]
Facing similar issue. Waiting for  v2.7.3
