### ISSUE TITLE
Cannot find an option to show or hide tabs

### ISSUE THREAD

**Issue by NapsterAhmed** [joeattardi/emoji-button#32]
Is there an option to show or hide specific categories tabs?
I tried to find an option to do that in the documentation but I couldn't find any.

Thank you for this amazing bundle.

**Comment by joeattardi** [comment]
I can definitely add this. Will try to get to it in the next few days. Thanks for the suggestion!

**Comment by joeattardi** [comment]
I have just released version 2.11.0 which has a new option, `categories`, which lets you specify which categories you want to have in the picker.

**Comment by NapsterAhmed** [comment]
Works good thank you. Just a couple of notes for this version:

- When the categories array gets sorted in a different order, the navigation icons are different than what it shows in the picker. The picker sorts fine though.
![Untitled2](https://user-images.githubusercontent.com/2592232/75413625-e5d0c280-58da-11ea-8771-f3bd5cff9890.jpg)

- Now after using the new version, recent shows undefined.
![Untitled](https://user-images.githubusercontent.com/2592232/75413533-a73b0800-58da-11ea-8fbb-c9a8bf08f780.jpg)

Other than that, everything is great. Again thank you for this great bundle.

**Comment by joeattardi** [comment]
Oops! Looks like I didn't test thoroughly enough. I will try to get that fixed this evening. Sorry about that.

**Comment by joeattardi** [comment]
Both of these issues should be fixed in 2.11.1
