### ISSUE TITLE
Mixed content warning on demo page

### ISSUE THREAD

**Issue by impressivewebs** [joeattardi/emoji-button#4]
Great tool!!

Just wanted to point out that the demo page is trying to load:

http://joeattardi.github.io:35729/livereload.js?snipver=1

Which is 'insecure' and so the page gives a mixed content warning in the browser.

**Comment by joeattardi** [comment]
Oops! I forgot to take care of that. Thanks!

**Comment by joeattardi** [comment]
This should be fixed now. It should only inject the livereload script now if the demo is running on `localhost`.

Thanks for reporting this!
