### ISSUE TITLE
Using the download emoji-button-2.12.1.min.js gives weird symbols.

### ISSUE THREAD

**Issue by st3fannldev** [joeattardi/emoji-button#40]
Hello,

So today I decided to include this script into one of my projects. We want it entirely working internally without needing external resources so I used the download emoji-button-2.12.1.min.js in a script to pull the icons. Yet this gives some weird symbols.. instead of the emojis.

Image here: https://i.imgur.com/jss5IDA.png

Any ideas?

**Comment by joeattardi** [comment]
This usually happens because of a character encoding issue. In your `index.html`, in the `head`, add this `meta` tag: `<meta charset="utf-8">`, see if that fixes the issue.

**Comment by st3fannldev** [comment]
That solved it, cheers!
