### ISSUE TITLE
Auto hide not working as expected

### ISSUE THREAD

**Issue by ezzabuzaid** [joeattardi/emoji-button#42]
Hi, 

I'm trying to keep the picker shown and to be closed manually
the current `autoHide` property seems not to work either the `showPreview`

moreover, it would be nice if there's an option to remove the categories bar at all

<img width="233" alt="Screen Shot 2020-04-05 at 1 16 20 AM" src="https://user-images.githubusercontent.com/29958503/78462480-132f3e00-76db-11ea-9912-c2744a60a889.png">

**Comment by joeattardi** [comment]
Can you please elaborate on what the issue is? When you say autoHide isn’t working, what is the problem you’re having?

**Comment by ezzabuzaid** [comment]
@joeattardi  thank you for that quick response!
I'm trying to have the picker persisted even if the user selects an emoji

**Comment by joeattardi** [comment]
Can you post a code snippet? Setting the `autoHide` option to `false` should have the behavior you're describing.

**Comment by ezzabuzaid** [comment]
I've already posted in the first comment

**Comment by joeattardi** [comment]
So are you saying when you use `autoHide: false` the picker still hides after selecting an emoji?

**Comment by ezzabuzaid** [comment]
![screencast-localhost_4200-2020 04](https://user-images.githubusercontent.com/29958503/78511883-e6e1f300-77a8-11ea-82f9-62b463d449df.gif)

Here's a demonstration.

**Comment by joeattardi** [comment]
I'm sorry, I'm still not able to reproduce this behavior based on the code snippet in your screenshot. Can you share the full source of your usage of the emoji picker?

**Comment by joeattardi** [comment]
Hi, just checking in again. Can you provide a full code example that exhibits the behavior you described, so I can try to debug it? Thank you. If I don’t hear from you soon I will probably close this for inactivity. Thanks.

**Comment by joeattardi** [comment]
Question: Are you passing these options to the `EmojiButton` constructor, or to the `togglePicker` or `showPicker` functions? These options only work when passed to the `EmojiButton` constructor.

**Comment by ezzabuzaid** [comment]
I'm sorry, I just saw the notifications

No, I'm passing them as an argument to `showPicker` method.
I've changed this and now I'm passing them to`EmojiButton` constructor and working perfectly!

so what is the usage of the `showPicker` option parameter?

**Comment by joeattardi** [comment]
The `showPicker` option parameter can be used to specify a custom position. I should update the docs to be more clear. Sorry for the mix-up!
