### ISSUE TITLE
Get emoji shortname / code?

### ISSUE THREAD

**Issue by dessalines** [joeattardi/emoji-button#43]
I'm using the twemoji, along with a parser in a textarea that converts all the `:smile:` etc to twemojis, and want to use this. I've found that the twemoji outputs html, but it would be really helpful if it included the name as a `data-` attribute, or anything that I could extract from the html.

**Comment by dessalines** [comment]
I found a way to do extract it with https://github.com/WebReflection/emoji-short-name : IE

```

**Comment by joeattardi** [comment]
All of the emoji data I use comes from the Unicode data, which does not include the short codes. I can certainly take a look at the package you linked and see if that would solve this problem.

**Comment by dessalines** [comment]
I'd like to use `style: 'twemoji'` so that it matches the rest of my site. Is the native emoji always in that html `alt` field that your twemoji style outputs? Because that would be a way I could do this.

**Comment by joeattardi** [comment]
Yes, the twemoji data always uses the native emoji character sequence I believe.

**Comment by dessalines** [comment]
Sweet, here's the code I have for this now:

```
  setupEmojiPicker() {
    emojiPicker.on('emoji', twemojiHtmlStr => {
      var el = document.createElement('div');
      el.innerHTML = twemojiHtmlStr;
      let nativeUnicode = (el.childNodes[0] as HTMLElement).getAttribute('alt');
      let shortName = `:${emojiShortName[nativeUnicode]}:`;
      ...
    });
  }
```

**Comment by joeattardi** [comment]
Glad you were able to find a solution!
