### ISSUE TITLE
Support for custom emojis category?

### ISSUE THREAD

**Issue by dessalines** [joeattardi/emoji-button#44]
I'd like to potentially add support for custom emojis section, like missive: https://github.com/missive/emoji-mart#custom-emojis

**Comment by joeattardi** [comment]
This is a great idea. Now that it supports twemoji, which are images, that opens the door to support custom emoji via images. I will try and see if I can add this in the 3.0 release that I’m currently working on.

**Comment by MetalMallard** [comment]
Looking forward this update ! would be awesome tobe able to add discord custom emoji for example !

**Comment by joeattardi** [comment]
I have added custom emoji support, this will be included in the upcoming 4.0.0 release.
