### ISSUE TITLE
Category shown by default

### ISSUE THREAD

**Issue by MorningSleeper** [joeattardi/emoji-button#46]
Hi, I noticed the picker scrolls by default down past the first category of Recent Emojis to the second category Smileys & Emotion. I understand one can click the Recent Emoji icon to get there but is there a way to specify the default category it goes to as I would like it to start at the top or Recent Emojis without any user action.

**Comment by joeattardi** [comment]
This isn’t currently supported, but I can definitely add this option. (Or, in the meantime, feel free to submit a PR, contributions are always welcomed! 😉)

**Comment by MorningSleeper** [comment]
Ok, thanks!

**Comment by joeattardi** [comment]
Going to leave this open as a reminder for me.

**Comment by joeattardi** [comment]
Done! 4.0.0 will have this feature.
