### ISSUE TITLE
The theme option seems to be useless

### ISSUE THREAD

**Issue by Anduin2017** [joeattardi/emoji-button#48]
I have installed: `"@joeattardi/emoji-button": "^3.0.0",`

But when I call it with:

```typescript
    public emoji(): void {
        const chatBox = <HTMLElement>document.querySelector('.chat-box');
        const input = <HTMLTextAreaElement>document.getElementById('chatInput');
        if(!this.picker) {
            this.picker = new EmojiButton();
            this.picker.on('emoji', emoji => {
                input.value += emoji;
            });
        }
        this.picker.togglePicker(chatBox, {
            position: 'top-start',
            zIndex: 20,
            theme: 'dark'
        });
    }
```

It still displays the light theme.

**Comment by Anduin2017** [comment]
Could you please check the `zIndex` property, It seems that it is still not working here.

**Comment by joeattardi** [comment]
The `theme` and `zIndex` options have to be passed to the `EmojiButton` constructor. Currently, you *can* pass an `options` object to the `togglePicker` function, however the only option that is supported there is `position`. 

I should update the documentation to reflect this, or as a future enhancement, I could support passing all of the options to `togglePIcker` / `showPicker` as well.
