### ISSUE TITLE
Some tabs is hard to click 😐

### ISSUE THREAD

**Issue by Anduin2017** [joeattardi/emoji-button#49]
![image](https://user-images.githubusercontent.com/19531547/80086741-bb268180-858c-11ea-88cc-29e73cceb137.png)

When I try to click it, I have to click the place which is right away from it ( about 5px ). And the third tab is the most difficult one to click.

**Comment by Anduin2017** [comment]
While I found that if I click a tab triple times, and everything works fine.

**Comment by joeattardi** [comment]
I just tested this out, and I didn't have any trouble clicking the tabs. Can you try the demo at https://emoji-button.js.org/ and see if you have the same issue there? BTW, you can click on the tab icons as well.

**Comment by Anduin2017** [comment]
Yes. I can repro it.

I have recorded a video:

https://probe.cdn.aiursoft.com/anduins-site/repro.mp4

**Comment by Anduin2017** [comment]
In the console:

![image](https://user-images.githubusercontent.com/19531547/80164572-ec926200-860b-11ea-8d8c-a9a59a35434b.png)

**Comment by joeattardi** [comment]
Aha! I can reproduce the issue if I clear my local storage. It looks like this issue occurs when there are no recent emojis stored in local storage. Yikes, this looks like a bad one. I will try to get a fix out ASAP!
