### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by adrianhuna** [joeattardi/emoji-button#5]
Hey, great library, thanks!

Here are two suggestions:
- the picker could not close after an emoji is clicked -> it makes sense that people want to click multiple emojis;
- the messages/placeholders could be configurable in order to achieve internalization

**Comment by joeattardi** [comment]
Thank you for the feedback! Those are both great suggestions and when I have some free time I will try to get those implemented.

**Comment by joeattardi** [comment]
I have implemented both of these suggestions in emoji-button@2.1.0, which I have just released.

Thanks!

**Comment by adrianhuna** [comment]
awesome!

**Comment by changeweb** [comment]
@joeattardi It would be great if Emoji data could be lazy load from another file. This will reduce bundle size of an app. Besides, it will be possible to dynamically add emoji data in that file.

What's your thought on this?

I appreciate your hard work.

**Comment by midzer** [comment]
@changeweb you can achieve the same via code splitting:
you can lazy load your `emoji.js` after button click. Have a look at my example here https://github.com/midzer/eisolzried/blob/db333f68e6971f2f632ce1011a5de6d63e84ec9e/_assets/js/modules/chatbox.js#L178
