### ISSUE TITLE
Setting autoFocusSearch to false does not prevent focus in search field

### ISSUE THREAD

**Issue by DaDom** [joeattardi/emoji-button#51]
Hi,

thanks a lot for your project, I like it a lot!
I was stumbling upon an issue though: I was trying to prevent the automatic change of focus to the search field by setting the autoFocusSearch option to false - but unfortunately the search field gets focused anyway.

Cannot say for sure, but maybe it's due to what happens here?
https://github.com/joeattardi/emoji-button/blob/master/src/index.ts#L140

This expression anyway resolves to true, or am I missing something?
Thanks!

**Comment by joeattardi** [comment]
Ah, you're right! This definitely isn't right. I was trying to default it to `true` if the option was not specified, but that's obviously the wrong way. I will try to get this fixed soon.

**Comment by DaDom** [comment]
Great, thanks a lot for getting back so quickly!

**Comment by joeattardi** [comment]
This should be fixed now in v3.0.3! Please let me know if you still have issues.
