### ISSUE TITLE
Z-index not working

### ISSUE THREAD

**Issue by sosherof** [joeattardi/emoji-button#54]
- The z-index option needs to be included in the outer most div (class="wrapper"), not the div just inside that (class="emoji-picker").  I'm guessing the outer-most div is being created by the popper, in which case not all of the options (i.e. the z-index) are getting passed.

- Passing additional options in the togglePicker seems to have no effect.   Looking at the code, didn't seem like the parameter was being used.

**Comment by Stefano1964** [comment]
Same here, zIndex is not working

**Comment by Stefano1964** [comment]
Added this to wrapper div
`this.wrapper.style.zIndex = this.options.zIndex,`
Now it's working

**Comment by joeattardi** [comment]
Feel free to submit a PR :)
