### ISSUE TITLE
Emoji always appended after the text

### ISSUE THREAD

**Issue by Poffen** [joeattardi/emoji-button#57]
Really nice work, I love it!

After testing it, I noticed that the emojis are always appended after the text. If I want to place emojis in the middle of a text (where I leave the cursor) I have to copy/paste, which is tedious work. I assume this is not intended behaviour of the app.

I would be nice also to have the option to display emoji short names, i.e. : smile : for db storage. Older versions of MySQL configured with utf8 charset (and not utf8mb4) struggle with 4-byte unicode characters.
 
Poffen

**Comment by joeattardi** [comment]
I assume your first comment is referring to the demo app at https://emoji-button.js.org - this is just a simplified demo and, as you pointed out, it always just appends the emoji to the end of the text field.

This is part of the demo app and *not* part of the library. The emoji picker fires an `emoji` event when an emoji is selected. You then can listen for this event and do whatever you want with the emoji, including get the current selection range and insert the emoji in the correct spot.

As for the short names, unfortunately that data is not available in the Unicode data files that I use to generate the emoji data.

**Comment by joeattardi** [comment]
For the short codes, you might be able to use the `node-emoji` package: https://www.npmjs.com/package/node-emoji to convert the short codes to and from the emoji characters.
