### ISSUE TITLE
Impossible to compile library

### ISSUE THREAD

**Issue by MJRomka** [joeattardi/emoji-button#59]
Sorry if I do something wrong, but I wanted to create a pull request to fix a bug. But when I clone project, make no changes, then do
npm install
npm link
npm run build
It compiles a bundle which contains an error: Unexpected token '}'
My npm version is 6.9.0

**Comment by joeattardi** [comment]
I just cloned a fresh copy of the library and was able to build and run the example. How are you pulling the library into your application?

**Comment by MJRomka** [comment]
I appologize mate, maybe it was something wrong in my project, but it complained about the library. I cleaned up everything and started from the scratch - worked fine this time. I've created my pull request and will close this issue.
