### ISSUE TITLE
position parameters is not working in Firefox

### ISSUE THREAD

**Issue by wellrats** [joeattardi/emoji-button#66]
Position parameter is not working on Firefox. "left",  "rigth", "top", "top-start" ... and so on

Configuration:

    // Emoji picker

    this.picker = new EmojiButton({ 
                                      zIndex:999, 
                                      emojiSize:"1.9em", 
                                      emojisPerRow:6, 
                                      position:"top-start", 
                                      rows: 5, 
                                      showPreview: false
                                  })

![Captura de Tela 2020-07-05 às 08 03 42](https://user-images.githubusercontent.com/3524744/86531270-25657780-be96-11ea-8a38-5f7911a6527f.png)
![Captura de Tela 2020-07-05 às 08 03 05](https://user-images.githubusercontent.com/3524744/86531274-28606800-be96-11ea-9ff0-d057ea81e2df.png)
![Captura de Tela 2020-07-05 às 08 02 30](https://user-images.githubusercontent.com/3524744/86531275-28f8fe80-be96-11ea-9d4f-61588ec894fb.png)

**Comment by joeattardi** [comment]
Hello,

I apologize for the delay in responding to your issue.

Can you show me the code where you are calling `showPicker`? Which element are you passing as the `referenceElement` argument?

Also, do you have this same issue in other browsers?

**Comment by joeattardi** [comment]
Hi, just pinging you again for this issue, could you take a look at my questions in my previous comment?

**Comment by joeattardi** [comment]
Closing this due to lack of response. Feel free to reopen with more details.
