### ISSUE TITLE
Problems to positioning picker in Popover component

### ISSUE THREAD

**Issue by Emeritvs** [joeattardi/emoji-button#67]
I'm trying to use this picker inside a Popover (Ionic component), but it only appears in this position on my screen:

![image](https://user-images.githubusercontent.com/43259638/86620628-06004480-bf93-11ea-9652-c12568aa1d01.png)

Sample of default popover usage:

![image](https://user-images.githubusercontent.com/43259638/86620801-61323700-bf93-11ea-9dbf-ac90262a02bd.png)

**Popover with picker (.ts) :** 

`
import EmojiButton from '@joeattardi/emoji-button';

@Component({
  selector: 'app-popoveremoji',
  templateUrl: './popoveremoji.page.html',
  styleUrls: ['./popoveremoji.page.scss'],
})
export class PopoveremojiPage implements OnInit {

  @ViewChild('pickerarea', {static: false}) pickerarea: HTMLElement;
  private picker = new EmojiButton({ position: 'auto' });

  constructor() { 
  }

  ngOnInit() {
    this.picker.showPicker(this.pickerarea);
  }

}`

**Popover with picker (.html) :**

`<ion-content #pickerarea>
</ion-content>`

**Comment by joeattardi** [comment]
Hi, sorry for the delay in responding to this.

So it looks like you are using `this.pickerArea` as the reference element when you show the picker. Where on the page is that element? The picker is positioned, using the Popper.js library, relative to the element you pass to `showPicker`.

**Comment by joeattardi** [comment]
Closing this due to lack of response. Feel free to reopen with more details.

**Comment by Emeritvs** [comment]
> Closing this due to lack of response. Feel free to reopen with more details. 

I solved my problem with this adjustment in CSS, it works well on all desktop screen resolutions:

div.wrapper {
    position: fixed;
    // transform: translate(130%, 38%);
    margin-left: calc(100vw - 470px);
    margin-top: calc( 100vh - 445px )
}

div.emoji-picker__preview {
    display: none !important;
}
div.emoji-picker__emojis{
    overflow-x: hidden;
    padding-left: 0px;
}
