### ISSUE TITLE
Issue with SSR?

### ISSUE THREAD

**Issue by hubert-ix** [joeattardi/emoji-button#76]
I don't think it's really a bug with the component itself, but it doesn't seem to work when used with a framework that uses server side rendering.

I've tried to use it with a clean install of Sapper (Svelte's SSR companion), and the compiler throws an error when I include the component.

Again, not really an issue with the component, but I thought I would mention it just in case.

**Comment by joeattardi** [comment]
That makes sense, I think. I can't see how this would work with server side rendering - it's not aware of any framework or anything like that. 

The markup could be rendered, I suppose, on the server side, but there wouldn't be any way to rehydrate/add event listeners/etc. 

There must be a way to call the EmojiButton constructor on the client side only once the app is rehydrated. I don't know much about SSR frameworks so I'm not sure.

**Comment by hubert-ix** [comment]
Yes, makes sense. I'm just getting started with SSR, so I'm not sure either. For some reason it breaks the compiler if I just import the package - even without instantiating a new EmojiButton().

**Comment by joeattardi** [comment]
What is the error that you get when you try to import the package?

**Comment by hubert-ix** [comment]
Ah, actually I got it to work! 

If it's useful to anyone, there were 2 important factors:
1) import the package with --save-dev
2) put almost everything in an onMount() function - or whatever the framework gives you to know the component has been added to the DOM

For reference here is what it looks like in Svelte/Sapper:

`<script>
import {onMount} from 'svelte';
import { EmojiButton } from '@joeattardi/emoji-button';

let emojiPicker;
let emojiButton;

onMount(() => {
  emojiPicker = new EmojiButton();
  emojiButton = document.querySelector('#emoji-button');
  emojiPicker.on('emoji', selection => {
    console.log(selection.emoji);
  });
});

function showEmojiPicker() {
  emojiPicker.togglePicker(emojiButton)
}
</script>

<button id="emoji-button" on:click|preventDefault={showEmojiPicker}>Emoji</button>`

Thanks a lot for being so proactive in replying, this gave me faith to stick to this component and find a way to get it to work :) (insert happy emoji here)

Now the last thing I have to solve is that somehow when I click on the emoji button, it scrolls back up the page... But doesn't do it if I click a second time.

**Comment by joeattardi** [comment]
Can you check the scrolling issue with the latest version and let me know if you still see it? I fixed a scrolling issue that may be the same cause as the one you're seeing.

Thanks!

**Comment by hubert-ix** [comment]
That did fix the issue! Awesome work, thanks so much!

**Comment by joeattardi** [comment]
Great! Glad to hear it. Thanks for checking.
