### ISSUE TITLE
Error sourcing emoji-button starting with 4.0.0

### ISSUE THREAD

**Issue by gabek** [joeattardi/emoji-button#77]
Looks like something changed with the 4.x version where importing it via a src tag now throws the following error:

```
Uncaught SyntaxError: Unexpected token 'export'
```

**Comment by gabek** [comment]
I found a workaround by using the browser modules functionality:

```
  <script type='module' src="/js/emoji.js"></script>
```

```
import { EmojiButton } from '/js/vendor/emojibutton.min.js'
```

**Comment by joeattardi** [comment]
Yes, sorry about that. As of version 4, Emoji Button is exported as an ES module only. So what you did is the correct course of action. 

I should make sure to note this in the docs. 

Sorry for the inconvenience!

**Comment by u20200522** [comment]
Hi - I am sorry for asking a very basic question.

This code works fine for version 3.0.3:

`	<script src="https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@3.0.3/dist/index.min.js"></script>
	<script>
		const trigger = document.querySelector('#emoji-button');
		const picker = new EmojiButton();

		picker.on('emoji', emoji => {
			document.querySelector('#user_text').value += emoji;
		});

		trigger.addEventListener('click', () => {
			picker.togglePicker(trigger);
		});
	</script>`

I am unsure about how I need to change the code to be able to use Version 4 - would you mind confirming please, how I should change my code to be able to use Version 4?

I changed the initial line to:

`<script type='module' src="https://cdn.jsdelivr.net/npm/@joeattardi/emoji-button@4.0.1/dist/index.min.js"></script>`

But that doesn't allow the code to work.

Any advice would be much appreciated, thanks.
