### ISSUE TITLE
npm ERR! code E404

### ISSUE THREAD

**Issue by muhammadobansa** [joeattardi/emoji-button#81]

**Comment by joeattardi** [comment]
I need more details.

What command were you trying to run? In which directory?

**Comment by muhammadobansa** [comment]
npm ERR! 404 Not Found - GET https://registry.npm.js.org/@joeattaradi%2femoj-button - Not found

**Comment by joeattardi** [comment]
What was the command you were running when this error occurred?

**Comment by muhammadobansa** [comment]
npm link @joeattaradi/emoji-button

**Comment by joeattardi** [comment]
It's `@joeattardi/emoji-button` - you spelled it wrong.

**Comment by muhammadobansa** [comment]
Yes it was the correct spelling

**Comment by joeattardi** [comment]
Look at how you spelled it - `@joeattaradi` - that's not correct, it's `@joeattardi`.

**Comment by joeattardi** [comment]
In the error you pasted above, you spelled it `@joeattaradi` - but if you did enter it correctly - did you run `npm link` from the root of the repository first?

**Comment by muhammadobansa** [comment]
No

**Comment by joeattardi** [comment]
Well that's why. 

You have to run `npm link` from the repository root first. This creates the link.

Then you run `npm link @joeattardi/emoji-button` from the `site` subdirectory, this consumes the link.

**Comment by joeattardi** [comment]
Closing due to lack of response.
