### ISSUE TITLE
Options for each category

### ISSUE THREAD

**Issue by websuvius** [joeattardi/emoji-button#86]
Hello.
Is it possible to set emojiSize and/or emojisPerRow for each category? Or for the custom category?
It could be very useful to manage a custom category with big gifs or stickers.
It could be useful also add a data-custom="true" on the category and not only on the single custom emoji.
Thanks

**Comment by joeattardi** [comment]
Currently, this is not possible.

The `emojiSize` and `emojisPerRow` properties determine the size of the CSS grid that make up the picker area, currently it's not supported to have different emojis be different sizes unfortunately.
