### ISSUE TITLE
Showing the picker triggers a jump in scroll position and wrong position

### ISSUE THREAD

**Issue by bgracie** [joeattardi/emoji-button#87]
To reproduce:
1. visit [the codesandbox](https://codesandbox.io/s/emoji-picker-position-bzp18?file=/src/index.js)
2. scroll down so that the picker should be able to comfortably open below the button:
3. click the button to activate the picker
4. the scroll position will jump up and the picker will open above the button, rather than below as specified by the `position` option

Other values of `position`, such as `auto` also seem to be affected.

It seems to be an issue with the picker rather than `popper`, because in a similar test `popper` performs as expected:
https://codesandbox.io/s/popper-position-j80fs?file=/src/index.js

Tested with chrome and firefox.

**Comment by joeattardi** [comment]
Just released version 4.0.3 which should have the fix for this. Sorry again for the delay on this one! Let me know if you still have the issue, but I updated the version in your codesandbox and I don't see the issue anymore. 

Thanks!

**Comment by bolandrm** [comment]
The issue seems to be resolved, thanks!
