### ISSUE TITLE
Question marks instead of emojis?

### ISSUE THREAD

**Issue by MorningSleeper** [joeattardi/emoji-button#88]
Hi, any idea why in 4.0.3 I am getting question marks for almost all emojis in the picker? Tested in latest Chrome and Firefox on PC with latest Windows 10 and latest Chrome on Android Phone. They show fine in 3.0.0. Tried clearing Chrome's cache, incognito mode and restarting. Tried specifying emojiVersion 1.0. If it matters, Windows 10 region is set to the United States.

https://stockbot.us/emojiPickerTest.php

![example](https://user-images.githubusercontent.com/8920632/90996197-e046f300-e572-11ea-8c21-69cb4789aa9a.gif)

```
import {  EmojiButton } from "/scripts/emoji-button-4.0.3.min.js?1";

window.addEventListener("load", function () {

  var emojiPickerMessage = new EmojiButton({
    autohide: true,
    autoFocusSearch: true,
    //categories: '[]',
    emojiSize: '1.8em',
    emojisPerRow: 8,
    //emojiVersion: '12.1',
    //emojiVersion: '1.0',
    position: 'bottom',
    recentsCount: 50,
    initialCategory: 'recents',
    //rootElement: body
    rows: 6,
    showCategoryButtons: true,
    showPreview: true,
    showSearch: true,
    showRecents: true,
    showVariants: true,
    style: 'native',
    theme: 'auto'

  });

  // message

  var emojiButtonMessage = document.getElementById('emojiButtonMessage');

  emojiButtonMessage.addEventListener('click', () => {
    emojiPickerMessage.togglePicker(emojiButtonMessage);
  });

  emojiPickerMessage.on('emoji', emoji => {
    document.getElementById('saMessage').value += emoji.emoji;
  });

});
```

**Comment by joeattardi** [comment]
Uh oh. I see it in your example as well. Let me try to reproduce locally.

**Comment by MorningSleeper** [comment]
ok, thanks for checking.

**Comment by joeattardi** [comment]
Can't reproduce it locally. I think it's a problem with your server. If you look at the raw JS being served by the server, the emoji data isn't in there, it's just the question marks:

```
 }, {
        emoji: "??",
        category: 1,
        name: "old man",
        variations: ["????", "????", "????", "????", "????"],
        version: "1.0"
    }, {
```

Your server needs to serve the JavaScript file with an encoding of utf-8. For example, here's the Content-Type header on my local server for the emoji data:

```
Content-Type: application/javascript; charset=utf-8
```

However, your server doesn't have the `charset=utf-8` part:

```
content-type: application/javascript
```

If you adjust your server configuration to serve JS files with the utf-8 encoding, you should be good to go.
