### ISSUE TITLE
Unwanted breaking change in 4.0.2

### ISSUE THREAD

**Issue by qortex** [joeattardi/emoji-button#89]
[This PR](https://github.com/joeattardi/emoji-button/commit/d49f7ee3d0e7a56a83e1e0b91e95c07ab6031580) introduces a breaking change in the API, since the added option is not optional.

Please make it optional so that the API stays stable? PR #84 already exists.

Pinning to previous version for now.

**Comment by joeattardi** [comment]
Sorry I missed that. Just published version 4.0.4 which makes the `rootElement` optional.

**Comment by qortex** [comment]
Great, thanks for the quick fix!
