### ISSUE TITLE
Spacing issues with emoji listing on Linux 

### ISSUE THREAD

**Issue by ianknauer** [joeattardi/emoji-button#9]
Hey there, i'm not sure if you intend to support Linux (specifically Ubuntu 18.04) but we're seeing some visual problems with the layout of emoji that have multiple icons within them. The icons seem to be wider so they're overlapping.

![Screenshot from 2019-10-31 10-13-18](https://user-images.githubusercontent.com/2685721/67970176-d01aed00-fbc7-11e9-844c-0d7cab8c239e.png)

**Comment by joeattardi** [comment]
I just tried this on an Ubuntu 18.04 VM after making the font change, and it seemed to work normally for me. Can you try the demo page again and let me know if it's working now? Thanks!

**Comment by ushmakapure** [comment]
@joeattardi looks like your fix worked! 
![Screenshot from 2019-11-05 11-28-25](https://user-images.githubusercontent.com/13123173/68239278-8a8f6300-ffbf-11e9-852a-73d6ed17da17.png)

**Comment by ianknauer** [comment]
> @joeattardi looks like your fix worked! Thank you 😊
> ![Screenshot from 2019-11-05 11-28-25](https://user-images.githubusercontent.com/13123173/68239278-8a8f6300-ffbf-11e9-852a-73d6ed17da17.png)

Great thanks for the fix on these two!
