### ISSUE TITLE
Picker alternates position over/under target

### ISSUE THREAD

**Issue by bgracie** [joeattardi/emoji-button#90]
Steps to reproduce:
1. set `position: bottom`;
2. scroll so that the picker would overflow the screen if it opened under the target
3. open and close the picker repeatedly
4. picker will alternately open over and under the target

(one would expect it to open in the same place given a constant scroll position)

See the codesandbox here: https://codesandbox.io/s/emoji-picker-position-bzp18?file=/src/index.js

Popper doesn't seem to have the same issue: https://codesandbox.io/s/popper-position-j80fs?file=/src/styles.css

**Comment by joeattardi** [comment]
Fixed in 4.1.0.

**Comment by bgracie** [comment]
Verified.   Thanks!
