### ISSUE TITLE
Firefox - Focus is not returned to proper element when using showAnimation option

### ISSUE THREAD

**Issue by jmlee2k** [joeattardi/emoji-button#91]
First off, thanks for this incredible library!

In Firefox, the picker (when `showAnimation` is `true`) "steals" the focus from the element which should be active.  For example, if you click on an input box to close the picker, you'll need to click on it a second time to restore the focus so you can type in it.

I've prepared a minimal test case here: https://codepen.io/jmlee2k/pen/oNxZwQj.

**Comment by joeattardi** [comment]
This will be fixed when 4.1.0 is released
