### ISSUE TITLE
Firefox - "Recent" category button is focused when opening picker and showAnimation is true

### ISSUE THREAD

**Issue by jmlee2k** [joeattardi/emoji-button#93]
You can see this on the demo at https://emoji-button.js.org/.  When the picker opens, the recent category button is focused after it opens.  This only happens when `showanimation` is `true` - you can see this by clicking the "don't show anim" button on the (unrelated) codepen here: https://codepen.io/jmlee2k/pen/oNxZwQj - it works as expected, while clicking the "show anim" button demonstrates the issue.

**Comment by joeattardi** [comment]
This will be fixed when 4.1.0 is released
