### ISSUE TITLE
Some emojis appear as two emojis

### ISSUE THREAD

**Issue by Armaldio** [joeattardi/emoji-button#98]
![image](https://user-images.githubusercontent.com/3089715/91868009-8e8a2100-ec74-11ea-979c-8678e2da64b0.png)

Some composed emojis appear like they are two emojis

**Comment by joeattardi** [comment]
Hm, this usually happens when the operating system does not support the latest Emoji version. Which OS and browser are you on?

**Comment by Armaldio** [comment]
I'm on W10 19042.450 and Brave Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit)
All up to date

**Comment by joeattardi** [comment]
I just tried this on a WIndows 10 system and got the same result. This is probably due to Windows 10 not supporting the latest Emoji version yet. If you use the Twemoji style, it should work as expected.
