### ISSUE TITLE
Where's thee compiled CSS/JS bundle?

### ISSUE THREAD

**Issue by prologic** [joeattardi/emoji-button#99]
Or in other words; I don't use `npm`.

**Comment by joeattardi** [comment]
You can load it from a CDN like unpkg: https://unpkg.com/@joeattardi/emoji-button@4.1.0/dist/index.js

It's exported as an ES module, which means you can import it directly from the CDN URL from within a `<script type="module">` tag, e.g.

```html
<script type="module">
  import { EmojiButton } from 'https://unpkg.com/@joeattardi/emoji-button@4.1.0/dist/index.js';

  const picker = new EmojiButton();
</script>
```

**Comment by prologic** [comment]
Thank you! 🙏 I was _hoping_ you could cut some Github release artefacts but this is okay too!
